#!/bin/bash
sed -i 's/P\.ATYPE/Parm\.Esoinn_setting\.Atype/g' *.py
sed -i 's/P\.E_INDEX/Parm\.Esoinn_setting\.Eindex/g' *.py
sed -i 's/Sysctrl/Strucdict/g' *.py
sed -i 's/PARAMS\["learning_rate"\]/Parm\.Neuralnetwork_setting\.Learningrate/g' *.py
sed -i 's/PARAMS\["learning_rate_dipole"\]/Parm\.Neuralnetwork_setting\.Learningratedipole/g' *.py
sed -i 's/PARAMS\["learning_rate_energy"\]/Parm\.Neuralnetwork_setting\.Learningrateenergy/g' *.py
sed -i 's/PARAMS\["learning_rate_boundary"\]/Parm\.Neuralnetwork_setting\.Learningratebooundary/g' *.py
sed -i 's/PARAMS\["SwitchEpoch_rate"\]/Parm\.Neuralnetwork_setting\.Switchrate/g' *.py
sed -i 's/PARAMS\["batch_size"\]/Parm\.Neuralnetwork_setting\.Batchsize/g' *.py
sed -i 's/PARAMS\["max_steps"\]/Parm\.Neuralnetwork_setting\.Maxsteps/g' *.py
sed -i 's/PARAMS\["momentum"\]/Parm\.Neuralnetwork_setting\.Momentum/g' *.py
sed -i 's/PARAMS\["tf_prec"\]/Parm\.Neuralnetwork_setting\.tfprec/g' *.py
sed -i 's/PARAMS\["max_checkpoints"\]/Parm\.Neuralnetwork_setting\.Maxcheckpoints/g' *.py
sed -i 's/PARAMS\["NeuronType"\]/Parm\.Neuralnetwork_setting\.NeuralType/g' *.py
sed -i 's/PARAMS\["networks_directory"\]/Parm\.Neuralnetwork_setting\.Networkpredix/g' *.py
sed -i 's/PARAMS\["AddEcc"\]/Parm\.Neuralnetwork_setting\.AddEcc/g' *.py
sed -i 's/PARAMS\["KeepProb"\]/Parm\.Neuralnetwork_setting\.Keepprob/g' *.py
sed -i 's/PARAMS\["InNormRoutine"\]/Parm\.Neuralnetwork_setting\.Innormroutine/g' *.py
sed -i 's/PARAMS\["OutNormRoutine"\]/Parm\.Neuralnetwork_setting\.Outnormroutine/g' *.py
sed -i 's/PARAMS\["MonitorSet"\]/Parm\.Neuralnetwork_setting\.Monitormset/g' *.py
sed -i 's/PARAMS\["GradScalar"\]/Parm\.Neuralnetwork_setting\.Scalar\["F"\]/g' *.py
sed -i 's/PARAMS\["EnergyScalar"\]/Parm\.Neuralnetwork_setting\.Scalar\["E"\]/g' *.py
sed -i 's/PARAMS\["DipoleScalar"\]/Parm\.Neuralnetwork_setting\.Scalar\["D"\]/g' *.py
sed -i 's/PARAMS\["HiddenLayers"\]/Parm\.Neuralnetwork_setting\.Structure/g' *.py
sed -i 's/PARAMS\["EECutoffOn"\]/Parm\.Neuralnetwork_setting\.EEcutoffon/g' *.py
sed -i 's/PARAMS\["EECutoff"\]/Parm\.Neuralnetwork_setting\.EEcutoff/g' *.py
sed -i 's/PARAMS\["EECutoffOff"\]/Parm\.Neuralnetwork_setting\.EEcutoffoff/g' *.py
sed -i 's/PARAMS\["DSFAlpha"\]/Parm\.Neuralnetwork_setting\.DSFAlpha/g' *.py
sed -i 's/PARAMS\["Elu_Width"\]/Parm\.Neuralnetwork_setting\.Eluwidth/g' *.py
sed -i 's/PARAMS\["AN1_a_Rc"\]/Parm\.Neuralnetwork_setting\.AN1_a_Rc/g' *.py
sed -i 's/PARAMS\["AN1_r_Rc"\]/Parm\.Neuralnetwork_setting\.AN1_r_Rc/g' *.py
sed -i 's/PARAMS\["AN1_zeta"\]/Parm\.Neuralnetwork_setting\.AN1_zeta/g' *.py
sed -i 's/PARAMS\["AN1_eta"\]/Parm\.Neuralnetwork_setting\.AN1_eta/g' *.py
sed -i 's/PARAMS\["AN1_num_a_As"\]/Parm\.Neuralnetwork_setting\.AN1_num_a_As/g' *.py
sed -i 's/PARAMS\["AN1_num_a_Rs"\]/Parm\.Neuralnetwork_setting\.AN1_num_a_Rs/g' *.py
sed -i 's/PARAMS\["AN1_num_r_Rs"\]/Parm\.Neuralnetwork_setting\.AN1_num_r_Rs/g' *.py
sed -i 's/PARAMS\["Profiling"\]/Parm\.Neuralnetwork_setting\.Profiling/g' *.py
sed -i 's/PARAMS\["test_freq"\]/Parm\.Neuralnetwork_setting\.Testfreq/g' *.py
sed -i 's/PARAMS\["sigmoid_alpha"\]/Parm\.Neuralnetwork_setting\.Sigmoidalpha/g' *.py
sed -i 's/PARAMS\["Classify"\]/Parm\.Neuralnetwork_setting\.Classify/g' *.py
sed -i 's/PARAMS\["ChopTo"\]/Parm\.Neuralnetwork_setting\.Chopto/g' *.py
sed -i 's/PARAMS\["TestRatio"\]/Parm\.Neuralnetwork_setting\.Testratio/g' *.py
sed -i 's/PARAMS\["MxTimePerElement"\]/Parm\.Neuralnetwork_setting\.Maxtimeperelement/g' *.py
sed -i 's/PARAMS\["MxMemPerElement"\]/Parm\.Neuralnetwork_setting\.Maxmemperelement/g' *.py
sed -i 's/PARAMS\["RandomizeData"\]/Parm\.Neuralnetwork_setting\.Randomizedata/g' *.py
