#!/bin/bash
sed -i 's/P\.ATYPE/GPARAMS\.Esoinn_setting\.Atype/g' *.py
sed -i 's/P\.E_INDEX/GPARAMS\.Esoinn_setting\.Eindex/g' *.py
sed -i 's/Sysctrl/Strucdict/g' *.py
sed -i 's/PARAMS\["learning_rate"\]/GPARAMS\.Neuralnetwork_setting\.Learningrate/g' *.py
sed -i 's/PARAMS\["learning_rate_dipole"\]/GPARAMS\.Neuralnetwork_setting\.Learningratedipole/g' *.py
sed -i 's/PARAMS\["learning_rate_energy"\]/GPARAMS\.Neuralnetwork_setting\.Learningrateenergy/g' *.py
sed -i 's/PARAMS\["learning_rate_boundary"\]/GPARAMS\.Neuralnetwork_setting\.Learningratebooundary/g' *.py
sed -i 's/PARAMS\["SwitchEpoch_rate"\]/GPARAMS\.Neuralnetwork_setting\.Switchrate/g' *.py
sed -i 's/PARAMS\["batch_size"\]/GPARAMS\.Neuralnetwork_setting\.Batchsize/g' *.py
sed -i 's/PARAMS\["max_steps"\]/GPARAMS\.Neuralnetwork_setting\.Maxsteps/g' *.py
sed -i 's/PARAMS\["momentum"\]/GPARAMS\.Neuralnetwork_setting\.Momentum/g' *.py
sed -i 's/PARAMS\["tf_prec"\]/GPARAMS\.Neuralnetwork_setting\.tfprec/g' *.py
sed -i 's/PARAMS\["max_checkpoints"\]/GPARAMS\.Neuralnetwork_setting\.Maxcheckpoints/g' *.py
sed -i 's/PARAMS\["NeuronType"\]/GPARAMS\.Neuralnetwork_setting\.NeuralType/g' *.py
sed -i 's/PARAMS\["networks_directory"\]/GPARAMS\.Neuralnetwork_setting\.Networkpredix/g' *.py
sed -i 's/PARAMS\["AddEcc"\]/GPARAMS\.Neuralnetwork_setting\.AddEcc/g' *.py
sed -i 's/PARAMS\["KeepProb"\]/GPARAMS\.Neuralnetwork_setting\.Keepprob/g' *.py
sed -i 's/PARAMS\["InNormRoutine"\]/GPARAMS\.Neuralnetwork_setting\.Innormroutine/g' *.py
sed -i 's/PARAMS\["OutNormRoutine"\]/GPARAMS\.Neuralnetwork_setting\.Outnormroutine/g' *.py
sed -i 's/PARAMS\["MonitorSet"\]/GPARAMS\.Neuralnetwork_setting\.Monitorset/g' *.py
sed -i 's/PARAMS\["GradScalar"\]/GPARAMS\.Neuralnetwork_setting\.Scalar\["F"\]/g' *.py
sed -i 's/PARAMS\["EnergyScalar"\]/GPARAMS\.Neuralnetwork_setting\.Scalar\["E"\]/g' *.py
sed -i 's/PARAMS\["DipoleScalar"\]/GPARAMS\.Neuralnetwork_setting\.Scalar\["D"\]/g' *.py
sed -i 's/PARAMS\["HiddenLayers"\]/GPARAMS\.Neuralnetwork_setting\.Structure/g' *.py
sed -i 's/PARAMS\["EECutoffOn"\]/GPARAMS\.Neuralnetwork_setting\.EEcutoffon/g' *.py
sed -i 's/PARAMS\["EECutoff"\]/GPARAMS\.Neuralnetwork_setting\.EEcutoff/g' *.py
sed -i 's/PARAMS\["EECutoffOff"\]/GPARAMS\.Neuralnetwork_setting\.EEcutoffoff/g' *.py
sed -i 's/PARAMS\["DSFAlpha"\]/GPARAMS\.Neuralnetwork_setting\.DSFAlpha/g' *.py
sed -i 's/PARAMS\["Elu_Width"\]/GPARAMS\.Neuralnetwork_setting\.Eluwidth/g' *.py
sed -i 's/PARAMS\["AN1_a_Rc"\]/GPARAMS\.Neuralnetwork_setting\.AN1_a_Rc/g' *.py
sed -i 's/PARAMS\["AN1_r_Rc"\]/GPARAMS\.Neuralnetwork_setting\.AN1_r_Rc/g' *.py
sed -i 's/PARAMS\["AN1_zeta"\]/GPARAMS\.Neuralnetwork_setting\.AN1_zeta/g' *.py
sed -i 's/PARAMS\["AN1_eta"\]/GPARAMS\.Neuralnetwork_setting\.AN1_eta/g' *.py
sed -i 's/PARAMS\["AN1_num_a_As"\]/GPARAMS\.Neuralnetwork_setting\.AN1_num_a_As/g' *.py
sed -i 's/PARAMS\["AN1_num_a_Rs"\]/GPARAMS\.Neuralnetwork_setting\.AN1_num_a_Rs/g' *.py
sed -i 's/PARAMS\["AN1_num_r_Rs"\]/GPARAMS\.Neuralnetwork_setting\.AN1_num_r_Rs/g' *.py
sed -i 's/PARAMS\["Profiling"\]/GPARAMS\.Neuralnetwork_setting\.Profiling/g' *.py
sed -i 's/PARAMS\["test_freq"\]/GPARAMS\.Neuralnetwork_setting\.Testfreq/g' *.py
sed -i 's/PARAMS\["sigmoid_alpha"\]/GPARAMS\.Neuralnetwork_setting\.Sigmoidalpha/g' *.py
sed -i 's/PARAMS\["Classify"\]/GPARAMS\.Neuralnetwork_setting\.Classify/g' *.py
sed -i 's/PARAMS\["ChopTo"\]/GPARAMS\.Neuralnetwork_setting\.Chopto/g' *.py
sed -i 's/PARAMS\["TestRatio"\]/GPARAMS\.Neuralnetwork_setting\.Testratio/g' *.py
sed -i 's/PARAMS\["MxTimePerElement"\]/GPARAMS\.Neuralnetwork_setting\.Maxtimeperelement/g' *.py
sed -i 's/PARAMS\["MxMemPerElement"\]/GPARAMS\.Neuralnetwork_setting\.Maxmemperelement/g' *.py
sed -i 's/PARAMS\["RandomizeData"\]/GPARAMS\.Neuralnetwork_setting\.Randomizedata/g' *.py
